name: Regression Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0'
      - name: Install curl
        run: sudo apt-get update && sudo apt-get install -y curl
      
      - name: Install Chrome
        run: sudo apt-get install -y google-chrome-stable

      - name: Install ChromeDriver
        run: |
          CHROME_DRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
          wget -N https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip -d $HOME/bin
          rm chromedriver_linux64.zip
        env:
          PATH: $HOME/bin:$PATH     
          
      - name: Add Selenium Package
        run: dotnet add ./BucStop/BucStop.csproj package Selenium.WebDriver
        
      - name: Restore dependencies
        run: dotnet restore ./BucStop/BucStop.csproj
      
      - name: Set permissions (optional)
        run: chmod +x ./BucStop/BucStop.csproj
        
      - name: Build
        run: dotnet build ./BucStop/BucStop.csproj
      
      - name: Run Project
        run: dotnet run --project ./BucStop/BucStop.csproj
        
      - name: Test project
        run: dotnet test ./BucStop/BucStop.csproj --logger "junit;LogFilePath=./BucStop/FirstTestTest.cs"

      - name: Debug Environment
        run: |
            ls -l
            dotnet --version
            pwd

      - name: Create test summary
        uses: test-summary/action@dist
        with:
          paths: results/**/*.xml
        if: always()
